Repository iTechArt-RubyLab/Ruby-Lab, pull requests merged in 2021-11, with the labels that each got.

#21 AndrewTehan/hometask-1
  AndrewTehan/hometask-1/hello_world.rb
Labels: Ready for Review

#13 Pivovar Andrew/hometask 1
  PivovarAndrew/hometask-1/helloworld.rb
Labels: approved

#15 TehanovAnton/hometask-1
  TehanovAnton/hometask-1/hometask_1.rb
Labels: Ready for Review

#40 AndrewTehan-hometask 2
  AndrewTehan/hometask-2/get_middle_charachter.rb
Labels: Ready for Review

#58 hometask-2/create get middle
  NastassiaBon/hometask-2/get_middle_charachter.rb
Labels: Ready for Review

#42 Skripchenkoveta hometask 2
  skripchenkoveta/hometask-2/get_middle_charachter.rb
Labels: Ready for Review

#62 Alhimick prog hometask 2
  alhimick-prog/hometask-2/get_middle_charachter.rb
Labels: approved

#39 TehanovAnton/hometask-2
  TehanovAnton/hometask-2/get_middle_character.rb
Labels: Ready for Review

#59 Pivovar Andrew/hometask 2
  PivovarAndrew/hometask-2/get_middle_character.rb
Labels: approved

#64 AndrewTehan-hometask-3
  AndrewTehan/hometask-3/cli.rb
  AndrewTehan/hometask-3/data
  AndrewTehan/hometask-3/math_functions.rb
  AndrewTehan/hometask-3/rainfall.rb
  AndrewTehan/hometask-3/rainfall_statistics.rb
Labels: Ready for Review

#73 Skripchenkoveta hometask 3
  skripchenkoveta/hometask-3/data.txt
  skripchenkoveta/hometask-3/rainfall.rb
Labels: Ready for Review

#82 Gek62/hometask-3
  Gek62/hometask-3/data
  Gek62/hometask-3/rainfall.rb
Labels: Ready for Review

#77 hometask-3/rainfall
  NastassiaBon/hometask-3/data.txt
  NastassiaBon/hometask-3/rainfall.rb
Labels: Ready for Review

#114 TehanovAnton/hometask-4
  TehanovAnton/hometask-4/my_array_rotate.rb
  TehanovAnton/hometask-4/my_array_rotate_benchmark.rb
  TehanovAnton/hometask-4/my_hash.rb
  TehanovAnton/hometask-4/my_hash_benchmark.rb
Labels: Ready for Review

#111 Sillitski/hometask_4
  qqqwww123cdv/hometask-4/my-array-rotate/my_array_rotate.rb
  qqqwww123cdv/hometask-4/my-array-rotate/my_array_rotate_benchmark.rb
  qqqwww123cdv/hometask-4/my-hash/my_hash.rb
  qqqwww123cdv/hometask-4/my-hash/my_hash_benchmark.rb
Labels: Ready for Review

#102 PandaGrom hometask 4
  PandaGrom/hometask-4/my_array_rotate.rb
  PandaGrom/hometask-4/my_array_rotate_benchmark.rb
  PandaGrom/hometask-4/my_hash.rb
  PandaGrom/hometask-4/my_hash_benchmark.rb
Labels: Ready for Review

#116 AndrewTehan/hometask-5
  AndrewTehan/hometask-5/4_1.sql
  AndrewTehan/hometask-5/4_10.sql
  AndrewTehan/hometask-5/4_11.sql
  AndrewTehan/hometask-5/4_2.sql
  AndrewTehan/hometask-5/4_3.sql
  AndrewTehan/hometask-5/4_4.sql
  AndrewTehan/hometask-5/4_5.sql
  AndrewTehan/hometask-5/4_6.sql
  AndrewTehan/hometask-5/4_7.sql
  AndrewTehan/hometask-5/4_8.sql
  AndrewTehan/hometask-5/4_9.sql
Labels: Ready for Review

#96 AndrewTehan/hometask-4
  AndrewTehan/hometask-4/Gemfile
  AndrewTehan/hometask-4/Gemfile.lock
  AndrewTehan/hometask-4/my_array_rotate.rb
  AndrewTehan/hometask-4/my_array_rotate_benchmark.rb
  AndrewTehan/hometask-4/my_hash.rb
  AndrewTehan/hometask-4/my_hash_benchmark.rb
Labels: Ready for Review

#115 Valeriyapetrova/hometask 5
  valeriyapetrova/hometask-5/4.1.sql
  valeriyapetrova/hometask-5/4.10.sql
  valeriyapetrova/hometask-5/4.11.sql
  valeriyapetrova/hometask-5/4.2.sql
  valeriyapetrova/hometask-5/4.3.sql
  valeriyapetrova/hometask-5/4.4.sql
  valeriyapetrova/hometask-5/4.5.sql
  valeriyapetrova/hometask-5/4.6.sql
  valeriyapetrova/hometask-5/4.7.sql
  valeriyapetrova/hometask-5/4.8.sql
  valeriyapetrova/hometask-5/4.9.sql
Labels: Ready for Review

#97 Valeriyapetrova/hometask 4
  valeriyapetrova/hometask-4/my_array_rotate.rb
  valeriyapetrova/hometask-4/my_array_rotate_benchmark.rb
  valeriyapetrova/hometask-4/my_hash.rb
  valeriyapetrova/hometask-4/my_hash_benchmark.rb
Labels: Ready for Review

#118 TehanovAnton/hometask-5
  TehanovAnton/hometask-5/hometask
  TehanovAnton/hometask-5/hometask_report.md
Labels: Ready for Review

#113 Mlshvch hometask 4
  mlshvch/hometask-4/README.md
  mlshvch/hometask-4/my_array_rotate.rb
  mlshvch/hometask-4/my_array_rotate_benchmark.rb
  mlshvch/hometask-4/my_hash.rb
  mlshvch/hometask-4/my_hash_benchmark.rb
  mlshvch/hometask-4/my_hash_benchmark_results.txt
  mlshvch/hometask-4/tests.txt
Labels: Ready for Review, Work in progress

#107 Slavahaim/hometask 4
  Slavahaim/hometask-4/my_array_rotate.rb
  Slavahaim/hometask-4/my_array_rotate_benchmark.rb
  Slavahaim/hometask-4/my_hash.rb
  Slavahaim/hometask-4/my_hash_benchmark.rb
Labels: Work in progress

#139 NastassiaBon/hometask-4
  NastassiaBon/hometask-4/my_array_rotate/my_array_benchmark.rb
  NastassiaBon/hometask-4/my_array_rotate/my_array_rotate.rb
  NastassiaBon/hometask-4/my_hash/my_hash.rb
  NastassiaBon/hometask-4/my_hash/my_hash_bencmark.rb
Labels: Ready for Review

#119 Pivovar Andrew/hometask-5
  PivovarAndrew/hometask-5/4.1.sql
  PivovarAndrew/hometask-5/4.10.sql
  PivovarAndrew/hometask-5/4.11.sql
  PivovarAndrew/hometask-5/4.2.sql
  PivovarAndrew/hometask-5/4.3.sql
  PivovarAndrew/hometask-5/4.4.sql
  PivovarAndrew/hometask-5/4.5.sql
  PivovarAndrew/hometask-5/4.6.sql
  PivovarAndrew/hometask-5/4.7.sql
  PivovarAndrew/hometask-5/4.8.sql
  PivovarAndrew/hometask-5/4.9.sql
Labels: approved

#99 Pivovar Andrew/hometask-4
  PivovarAndrew/hometask-4/benchmark/my_array_rotate_benchmark.rb
  PivovarAndrew/hometask-4/benchmark/my_hash_benchmark.rb
  PivovarAndrew/hometask-4/main.rb
  PivovarAndrew/hometask-4/model/my_array_rotate.rb
  PivovarAndrew/hometask-4/model/my_hash.rb
Labels: approved

#137 silitski_hometask/5
  qqqwww123cdv/hometask-5/1.sql
  qqqwww123cdv/hometask-5/10.sql
  qqqwww123cdv/hometask-5/11.sql
  qqqwww123cdv/hometask-5/2.sql
  qqqwww123cdv/hometask-5/3.sql
  qqqwww123cdv/hometask-5/4.sql
  qqqwww123cdv/hometask-5/5.sql
  qqqwww123cdv/hometask-5/6.sql
  qqqwww123cdv/hometask-5/7.sql
  qqqwww123cdv/hometask-5/8.sql
  qqqwww123cdv/hometask-5/9.sql
Labels: Ready for Review

#125 NastassiaBon/hometask-5
  NastassiaBon/hometask-5/4.1.sql
  NastassiaBon/hometask-5/4.10.sql
  NastassiaBon/hometask-5/4.11.sql
  NastassiaBon/hometask-5/4.2.sql
  NastassiaBon/hometask-5/4.3.sql
  NastassiaBon/hometask-5/4.4.sql
  NastassiaBon/hometask-5/4.5.sql
  NastassiaBon/hometask-5/4.6.sql
  NastassiaBon/hometask-5/4.7.sql
  NastassiaBon/hometask-5/4.8.sql
  NastassiaBon/hometask-5/4.9.sql
Labels: Ready for Review

#138 Skripchenkoveta/hometask 5
  skripchenkoveta/hometask-5/4-1.sql
  skripchenkoveta/hometask-5/4-10.sql
  skripchenkoveta/hometask-5/4-11.sql
  skripchenkoveta/hometask-5/4-2.sql
  skripchenkoveta/hometask-5/4-3.sql
  skripchenkoveta/hometask-5/4-4.sql
  skripchenkoveta/hometask-5/4-5.sql
  skripchenkoveta/hometask-5/4-6.sql
  skripchenkoveta/hometask-5/4-7.sql
  skripchenkoveta/hometask-5/4-8.sql
  skripchenkoveta/hometask-5/4-9.sql
Labels: Ready for Review

#122 Gek62/hometask-5
  Gek62/hometask-5/5.4.1.sql
  Gek62/hometask-5/5.4.10.sql
  Gek62/hometask-5/5.4.11.sql
  Gek62/hometask-5/5.4.2.sql
  Gek62/hometask-5/5.4.3.sql
  Gek62/hometask-5/5.4.4.sql
  Gek62/hometask-5/5.4.5.sql
  Gek62/hometask-5/5.4.6.sql
  Gek62/hometask-5/5.4.7.sql
  Gek62/hometask-5/5.4.8.sql
  Gek62/hometask-5/5.4.9.sql
Labels: Ready for Review

#155 PivovarAndrew/hometask-6
  PivovarAndrew/hometask-4/.hound.yml
  PivovarAndrew/hometask-4/.rubocop.yml
  PivovarAndrew/hometask-4/rspec/my_hash_spec.rb
  PivovarAndrew/hometask-6/GemFile
  PivovarAndrew/hometask-6/GemFile.lock
  PivovarAndrew/hometask-6/file/data.csv
  PivovarAndrew/hometask-6/main.rb
  PivovarAndrew/hometask-6/model/csv_writer.rb
  PivovarAndrew/hometask-6/model/driver_setup.rb
  PivovarAndrew/hometask-6/model/parser.rb
  PivovarAndrew/hometask-6/model/scrapper.rb
Labels: approved

#101 Skripchenkoveta hometask 4
  skripchenkoveta/hometask-4/my_array_rotate.rb
  skripchenkoveta/hometask-4/my_array_rotate_benchmark.rb
  skripchenkoveta/hometask-4/my_hash.rb
  skripchenkoveta/hometask-4/my_hash_benchmark.rb
Labels: Ready for Review

#151 TehanovAnton/hometask-6
  .rubocop.yml
  TehanovAnton/hometask-4/spec/my_hash_spec.rb
  TehanovAnton/hometask-6/Gemfile
  TehanovAnton/hometask-6/Gemfile.lock
  TehanovAnton/hometask-6/configs/onliner.json
  TehanovAnton/hometask-6/reports/onliner/28112021_224156.csv
  TehanovAnton/hometask-6/scrapper.rb
  TehanovAnton/hometask-6/scrapper/config.rb
  TehanovAnton/hometask-6/scrapper/parser.rb
  TehanovAnton/hometask-6/scrapper/report.rb
Labels: Ready for Review
