Repository iTechArt-RubyLab/Ruby-Lab, pull requests merged in 2021-12, with the labels that each got.

#156 Mlshvch hometask 6
  mlshvch/hometask-4/spec/my_hash_spec.rb
  mlshvch/hometask-6/Gemfile
  mlshvch/hometask-6/Gemfile.lock
  mlshvch/hometask-6/README.md
  mlshvch/hometask-6/data.csv
  mlshvch/hometask-6/scrapper.rb
Labels: bug, Work in progress

#173 KarinaKlevzhits/hometask-2
  KarinaKlevzhits/hometask_2/get_middle_charachter.rb
Labels: Ready for Review

#169 WhatWasThatt/hometask-1
  WhatWasThatt/hometask-1/hello_world.rb
Labels: Ready for Review

#175 WhatWasThatt/hometask-2
  WhatWasThatt/get_middle_character.rb
Labels: Ready for Review

#177 twill11/hometask-2
  twill11/hometask-2/get_middle_character.rb
  twill11/hometask-2/run_cli.rb
  twill11/hometask-2/validator.rb
Labels: approved

#148 AndrewTehan/hometask-6
  .rubocop.yml
  AndrewTehan/hometask-4/my_hash.rb
  AndrewTehan/hometask-4/spec/my_hash_spec.rb
  AndrewTehan/hometask-6/.gitignore
  AndrewTehan/hometask-6/Gemfile
  AndrewTehan/hometask-6/Gemfile.lock
  AndrewTehan/hometask-6/scrapper.rb
  AndrewTehan/hometask-6/scrapper/file_writer.rb
  AndrewTehan/hometask-6/scrapper/parser.rb
  AndrewTehan/hometask-6/scrapper/rules/onliner.yml
Labels: Ready for Review

#165 Valeriyapetrova/hometask 6
  valeriyapetrova/hometask-6/onliner/.DS_Store
  valeriyapetrova/hometask-6/onliner/Gemfile
  valeriyapetrova/hometask-6/onliner/Gemfile.lock
  valeriyapetrova/hometask-6/onliner/config.rb
  valeriyapetrova/hometask-6/onliner/constants.rb
  valeriyapetrova/hometask-6/onliner/parser.rb
  valeriyapetrova/hometask-6/spec/rspec_myhash.rb
Labels: Ready for Review

#159 Skripchenkoveta hometask 6
  skripchenkoveta/hometask-4/spec/my_hash_spec.rb
  skripchenkoveta/hometask-6/Gemfile
  skripchenkoveta/hometask-6/Gemfile.lock
  skripchenkoveta/hometask-6/my_hash_spec.rb
Labels: needs rework

#176 Valikkkkk/hometask 2
  VALIKKKKK/hometask-2/get_middle_charachter.rb
Labels: Ready for Review

#174 KarinaKlevzhits/hometask-3
  KarinaKlevzhits/hometask_3/data.txt
  KarinaKlevzhits/hometask_3/rainfall.rb
Labels: Ready for Review

#180 twill11/hometask-3
  twill11/hometask-3/data.txt
  twill11/hometask-3/lib/data_converter.rb
  twill11/hometask-3/lib/data_reader.rb
  twill11/hometask-3/lib/rainfall.rb
  twill11/hometask-3/lib/validator.rb
  twill11/hometask-3/run_cli.rb
Labels: approved

#179 VALIKKKKK/hometask-3
  VALIKKKKK/hometask-3/cli.rb
  VALIKKKKK/hometask-3/data.txt
  VALIKKKKK/hometask-3/lib/rainfall.rb
Labels: Ready for Review

#178 WhatWasThatt/hometask-3
  WhatWasThatt/hometask-3/.gitignore
  WhatWasThatt/hometask-3/.rspec
  WhatWasThatt/hometask-3/Gemfile
  WhatWasThatt/hometask-3/Gemfile.lock
  WhatWasThatt/hometask-3/README.md
  WhatWasThatt/hometask-3/data.txt
  WhatWasThatt/hometask-3/lib/calculators/rainfall/calculator.rb
  WhatWasThatt/hometask-3/lib/calculators/rainfall/operations/average.rb
  WhatWasThatt/hometask-3/lib/calculators/rainfall/operations/base.rb
  WhatWasThatt/hometask-3/lib/calculators/rainfall/operations/variance.rb
  WhatWasThatt/hometask-3/lib/utils/data_parser.rb
  WhatWasThatt/hometask-3/lib/utils/data_reader.rb
  WhatWasThatt/hometask-3/rainfall_cli.rb
  WhatWasThatt/hometask-3/spec/lib/calculators/rainfall/calculator_spec.rb
  WhatWasThatt/hometask-3/spec/lib/calculators/rainfall/operations/average_spec.rb
  WhatWasThatt/hometask-3/spec/lib/calculators/rainfall/operations/variance_spec.rb
  WhatWasThatt/hometask-3/spec/lib/utils/data_parser_spec.rb
  WhatWasThatt/hometask-3/spec/lib/utils/data_reader_spec.rb
  WhatWasThatt/hometask-3/spec/spec_helper.rb
Labels: Ready for Review

#186 twill11/hometask-4
  twill11/hometask-4/my_array/class_array.rb
  twill11/hometask-4/my_array/my_array_rotate_benchmark.rb
  twill11/hometask-4/my_array/my_lab_rotate.rb
  twill11/hometask-4/my_hash/my_hash.rb
  twill11/hometask-4/my_hash/my_hash_benchmark.rb
Labels: approved

#184 KarinaKlevzhits/hometask-5
  KarinaKlevzhits/hometask_5/#4.1.sql
  KarinaKlevzhits/hometask_5/#4.10.sql
  KarinaKlevzhits/hometask_5/#4.11.sql
  KarinaKlevzhits/hometask_5/#4.2.sql
  KarinaKlevzhits/hometask_5/#4.3.sql
  KarinaKlevzhits/hometask_5/#4.4.sql
  KarinaKlevzhits/hometask_5/#4.5.sql
  KarinaKlevzhits/hometask_5/#4.6.sql
  KarinaKlevzhits/hometask_5/#4.7.sql
  KarinaKlevzhits/hometask_5/#4.8.1.sql
  KarinaKlevzhits/hometask_5/#4.8.sql
  KarinaKlevzhits/hometask_5/#4.9.sql
Labels: Ready for Review

#185 KarinaKlevzhits/hometask-4
  KarinaKlevzhits/hometask_4/my_array_rotate.rb
  KarinaKlevzhits/hometask_4/my_array_rotate_benchmark.rb
  KarinaKlevzhits/hometask_4/my_hash.rb
  KarinaKlevzhits/hometask_4/my_hash_benchmark.rb
Labels: Ready for Review

#187 twill11/hometask-5
  twill11/hometask-5/4.1.sql
  twill11/hometask-5/4.10.sql
  twill11/hometask-5/4.11.sql
  twill11/hometask-5/4.2.sql
  twill11/hometask-5/4.3.sql
  twill11/hometask-5/4.4.sql
  twill11/hometask-5/4.5.sql
  twill11/hometask-5/4.6.sql
  twill11/hometask-5/4.7.sql
  twill11/hometask-5/4.8.sql
  twill11/hometask-5/4.9.sql
Labels: approved

#188 VALIKKKKK/hometask-4
  VALIKKKKK/hometask-4/my_array_rotate.rb
  VALIKKKKK/hometask-4/my_array_rotate_benchmark.rb
  VALIKKKKK/hometask-4/my_hash.rb
  VALIKKKKK/hometask-4/my_hash_benchmark.rb
Labels: approved

#189 VALIKKKKK/hometask-5
  VALIKKKKK/hometask-5/4.1.sql
  VALIKKKKK/hometask-5/4.10.sql
  VALIKKKKK/hometask-5/4.11.sql
  VALIKKKKK/hometask-5/4.2.sql
  VALIKKKKK/hometask-5/4.3.sql
  VALIKKKKK/hometask-5/4.4.sql
  VALIKKKKK/hometask-5/4.5.sql
  VALIKKKKK/hometask-5/4.6.sql
  VALIKKKKK/hometask-5/4.7.sql
  VALIKKKKK/hometask-5/4.8.sql
  VALIKKKKK/hometask-5/4.9.sql
Labels: Ready for Review

#182 WhatWasThatt/hometask-4
  WhatWasThatt/hometask-4/my_array_rotate.rb
  WhatWasThatt/hometask-4/my_array_rotate_benchmark.rb
  WhatWasThatt/hometask-4/my_hash.rb
  WhatWasThatt/hometask-4/my_hash_benchmark.rb
  WhatWasThatt/hometask-4/my_rotate.rb
Labels: Ready for Review

#183 WhatWasThatt/hometask-5
  WhatWasThatt/hometask-5/1.sql
  WhatWasThatt/hometask-5/10.sql
  WhatWasThatt/hometask-5/11.sql
  WhatWasThatt/hometask-5/2.sql
  WhatWasThatt/hometask-5/3.sql
  WhatWasThatt/hometask-5/4.sql
  WhatWasThatt/hometask-5/5.sql
  WhatWasThatt/hometask-5/6.sql
  WhatWasThatt/hometask-5/7.sql
  WhatWasThatt/hometask-5/8.sql
  WhatWasThatt/hometask-5/9.sql
Labels: Ready for Review

#193 WhatWasThatt/hometask-6
  WhatWasThatt/hometask-2/get_middle_character.rb
  WhatWasThatt/hometask-4/.rspec
  WhatWasThatt/hometask-4/.rubocop.yml
  WhatWasThatt/hometask-4/Gemfile
  WhatWasThatt/hometask-4/Gemfile.lock
  WhatWasThatt/hometask-4/spec/my_hash_spec.rb
  WhatWasThatt/hometask-4/spec/spec_helper.rb
Labels: Ready for Review

#194 twill11/hometask-6
  twill11/hometask-6/Gemfile
  twill11/hometask-6/Gemfile.lock
  twill11/hometask-6/file/dogs.csv
  twill11/hometask-6/lib/csv_writer.rb
  twill11/hometask-6/lib/parser.rb
  twill11/hometask-6/lib/photo.rb
  twill11/hometask-6/run_cli.rb
Labels: approved

#195 twill11/hometask-6-2
  twill11/hometask-4/.rubocop.yml
  twill11/hometask-4/Gemfile
  twill11/hometask-4/Gemfile.lock
  twill11/hometask-4/spec/my_hash_spec.rb
  twill11/hometask-4/spec/spec_helper.rb
Labels: approved

#197 Valikkkkk/hometask 6
  VALIKKKKK/hometask-4/.gitignore
  VALIKKKKK/hometask-4/.rspec
  VALIKKKKK/hometask-4/.rubocop.yml
  VALIKKKKK/hometask-4/Gemfile
  VALIKKKKK/hometask-4/Gemfile.lock
  VALIKKKKK/hometask-4/my_hash.rb
  VALIKKKKK/hometask-4/spec/my_hash_spec.rb
  VALIKKKKK/hometask-4/spec/spec_helper.rb
  VALIKKKKK/hometask-6/Gemfile
  VALIKKKKK/hometask-6/Gemfile.lock
  VALIKKKKK/hometask-6/lib/car_data.rb
  VALIKKKKK/hometask-6/lib/cars_data.rb
  VALIKKKKK/hometask-6/lib/data_fetcher.rb
  VALIKKKKK/hometask-6/lib/file_writer.rb
  VALIKKKKK/hometask-6/lib/response_parser.rb
  VALIKKKKK/hometask-6/requests_onliner.rb
Labels: approved

#196 WhatWasThatt/hometask-6-1
  WhatWasThatt/hometask-6/.rubocop.yml
  WhatWasThatt/hometask-6/Gemfile
  WhatWasThatt/hometask-6/Gemfile.lock
  WhatWasThatt/hometask-6/lib/characters/fetcher.rb
  WhatWasThatt/hometask-6/lib/characters/list.rb
  WhatWasThatt/hometask-6/lib/characters/parser.rb
  WhatWasThatt/hometask-6/lib/characters/processor.rb
  WhatWasThatt/hometask-6/lib/characters/writers/csv.rb
  WhatWasThatt/hometask-6/lib/deaths/fetcher.rb
  WhatWasThatt/hometask-6/lib/deaths/parser.rb
  WhatWasThatt/hometask-6/lib/deaths/processor.rb
  WhatWasThatt/hometask-6/lib/deaths/writers/csv.rb
  WhatWasThatt/hometask-6/lib/run_cli.rb
Labels: Work in progress

#190 KarinaKlevzhits/hometask-6
  KarinaKlevzhits/hometask_6/.rubocop.yml
  KarinaKlevzhits/hometask_6/Gemfile
  KarinaKlevzhits/hometask_6/Gemfile.lock
  KarinaKlevzhits/hometask_6/file.xml
  KarinaKlevzhits/hometask_6/services/currency_queries.rb
  KarinaKlevzhits/hometask_6/services/data_loader.rb
  KarinaKlevzhits/hometask_6/services/data_parser.rb
  KarinaKlevzhits/hometask_6/services/data_recorder.rb
  KarinaKlevzhits/hometask_6/services/find_rate.rb
  KarinaKlevzhits/hometask_6/top_5_falls_for_currency.rb
Labels: Ready for Review

#198 KarinaKlevzhits/hometask6-2
  KarinaKlevzhits/.DS_Store
  KarinaKlevzhits/hometask_4/.rspec
  KarinaKlevzhits/hometask_4/.rubocop.yml
  KarinaKlevzhits/hometask_4/Gemfile
  KarinaKlevzhits/hometask_4/Gemfile.lock
  KarinaKlevzhits/hometask_4/my_hash.rb
  KarinaKlevzhits/hometask_4/spec/lib/my_hash_spec.rb
  KarinaKlevzhits/hometask_4/spec/spec_helper.rb
Labels: Ready for Review
